FROM litespeedtech/litespeed:6.2.2-lsphp81

# Set working directory
WORKDIR /var/www/vhosts

# Copy all files from the current directory to the container
COPY . .

# If you need to run any additional setup commands, add them here
# For example:
# RUN composer install
# RUN npm install && npm run build

# The CMD instruction is not needed here as it's defined in the docker-compose.yml file
