version: '3'
services:
  mysql:
    image: mariadb:10.11
    command: --max_allowed_packet=256M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    ports:
       - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always  
  litespeed:
    image: litespeedtech/openlitespeed:1.7.16-lsphp81
    volumes:
        - ./lsws/conf:/usr/local/lsws/conf
        - ./lsws/admin/conf:/usr/local/lsws/admin/conf
        - ./bin/container:/usr/local/bin
        - ./sites:/var/www/vhosts/
        - ./acme:/root/.acme.sh/
        - ./logs:/usr/local/lsws/logs/
    ports:
      - 18080:80
      - 18443:443
      - 18443:443/udp
      - 17080:7080
    restart: always
    environment:
      TZ: ${TimeZone}
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 18081:80
    environment:
      - PMA_HOST=mysql
    restart: always
